
typedef struct card{
	char *face;
	char *suit;

} Card;


/*LIST OF QUESTIONS FOR JOHN*/

/*ARRANGEMENT - STRUCT FOR CARDS...IS DECK A CARD OR IS DECK A DECK*/
/*FLOW FOR DEAL (IF CURRENT DEAL WORKS) TO TRACK TO PLAYER/MONTE CARLO ATTRIBUTES FOR HAND ASSESSMENT*/
/*MONTE CARLO STARTER - HOW SHOULD THAT FOR LOOP RUN*/
/*WHERE SHOULD GAME CONTROL - STDOUT PRINTING - BE HANDLED? MAIN OR SAY PLAYER? */


